# paperclip:
#   storage: s3
#   s3_credentials:
#     access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY", nil) %>
#     secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY", nil) %>
#   s3_region: us-east-1
#   s3_permissions: private
#   bucket: "nucore-production"
