name: Run test suite

# Don't want to run this when tags are pushed
on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  run-rspec-engines:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      mysql:
        image: mysql:8.0.28
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_ROOT_HOST: "%"
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    container:
      image: wyeworkshub/ruby-node-chrome-pack:ruby3.4.4-node22
    env:
      RAILS_ENV: test
      RAILS_TEST_COMPILED_ASSETS: true
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rails

      - name: Glob match
        uses: tj-actions/glob@v22
        id: glob
        with:
          files: |
            vendor/engines/*/spec/**/*_spec.rb

      - run: bundle exec rails assets:precompile
      - run: bundle exec rspec ${{ steps.glob.outputs.paths }}

  run-rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      mysql:
        image: mysql:8.0.28
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_ROOT_HOST: "%"
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    container:
      image: wyeworkshub/ruby-node-chrome-pack:ruby3.4.4-node22
    env:
      RAILS_ENV: test
      RAILS_TEST_COMPILED_ASSETS: true
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      PARALLEL_TEST_PROCESSORS: 4
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rails
      # Uncomment below to open ssh tunnel for debugging
      # - uses: mxschmitt/action-tmate@v3
      - run: bundle exec rails parallel:create
      - run: bundle exec rails parallel:load_schema
      - run: bundle exec rails assets:precompile
      - run: bundle exec rails parallel:spec

  run-teaspoon:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      mysql:
        image: mysql:8.0.28
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_ROOT_HOST: "%"
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size="2g"
    container:
      image: wyeworkshub/ruby-node-chrome-pack:ruby3.4.4-node22
    env:
      TEASPOON_RAILS_ENV: test
      RAILS_ENV: test
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      TEST_APP_PORT: 3000
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rails
      - run: yarn build
      - run: bundle exec rake teaspoon

  run-rubocop:
    runs-on: ubuntu-latest
    container:
      image: wyeworkshub/ruby-node-chrome-pack:ruby3.4.4-node22
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bundler
      - run: bundle exec rubocop
